### PR TITLE
Add logo under the CC Attribution-ShareAlike 4.0 International license

### PR DESCRIPTION
**Pull request by benjyw**

### CODE REVIEW

**Review by stuhood — APPROVED** [review]

**Review by jsirois — APPROVED** [review]

**Comment by benjyw** [comment]
Hi @desandro - hoping you can give an approving review to this PR, to validate the logo ownership assertions made in it. Thanks!

**Comment by desandro** [comment]
👍

**Review by desandro — COMMENTED** [review]
I approve

**Comment by benjyw** [comment]
Thanks @desandro, I hope you're well.

**Pull request merged**
